### PR TITLE
Close rd pipe after sending the request

### LINKED ISSUE #1032: Too many open file descriptors
Hi!

We're using the agent with [EventMachine](https://github.com/eventmachine/eventmachine/).

However, we're facing a problem. We have too many open file descriptors.

They are all pipes:

```
> ls -l /proc/1111/fd
total 0
...
l-wx------ 1 user group 64 Feb 31 00:11 12 -> 'pipe:[39797]'
lr-x------ 1 user group 64 Feb 31 00:15 127 -> 'pipe:[222222]'
...
```

When I try to get more info on one of the pipes:

```
lsof | grep 222222
ruby       5646                user   13r     FIFO               0,13       0t0     222222 pipe
base.rb:1  5646  5978          user   13r     FIFO               0,13       0t0     222222 pipe
worker-1   5646  5979          user   13r     FIFO               0,13       0t0     222222 pipe
io-worker  5646  5983          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7562          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7563          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7564          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7565          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7566          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7567          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7568          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7569          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7570          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7571          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7572          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7573          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7574          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7575          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7576          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7577          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7578          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7579          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7580          user   13r     FIFO               0,13       0t0     222222 pipe
eventmach  5646  7581          user   13r     FIFO               0,13       0t0     222222 pipe
io-worker  5646 25377          user   13r     FIFO               0,13       0t0     222222 pipe
http.rb:1  5646 26233          user   13r     FIFO               0,13       0t0     222222 pipe
```

I guess it's happening due to how the worker sends the transactions and spans to the server.

I'm looking for any help on how to solve this.

Thanks in advance.

## Steps to reproduce

Described in the following repository: https://github.com/matheussilvasantos/file_descriptor_leak.

### PR DESCRIPTION
**Pull request by matheussilvasantos**
## What does this pull request do?

It closes the read pipe after sending the HTTP request.

## Why is it important?

Not closing the read pipe causes a growing number of open file descriptors.

## Observations

I've updated the `closed?` method. This way, the current tests will cover the change.

## Checklist

- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/). 
- [x] My code follows the style guidelines of this project (See `.rubocop.yml`)
- [x] I have rebased my changes on top of the latest master branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-ruby/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
- [x] I have made corresponding changes to the documentation
- [x] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
- [x] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)
- [ ] Added an API method or config option? Document in which version this will be introduced

## Related issues

- Closes #1032

### CODE REVIEW

File: lib/elastic_apm/transport/connection/http.rb [hunk 1]
```diff
@@ -107,6 +107,7 @@ def open_request_in_thread(url)
           Thread.new do
             begin
               resp = post(url, body: @rd, headers: @headers.chunked.to_h)
+              @rd&.close
```
Comment (mikker) [inline lib/elastic_apm/transport/connection/http.rb:110]: We should probably add an `ensure` to the surrounding `begin` and put this there instead? Making sure that even if the request raises somehow, we still close the thing.

**Review by mikker — COMMENTED** [review]
This looks good, thanks! I'll let the tests run.

**Comment by mikker** [comment]
jenkins, run the tests

File: lib/elastic_apm/transport/connection/http.rb (hunk 1 above)
Comment (matheussilvasantos) [reply lib/elastic_apm/transport/connection/http.rb]: Good spot. Done.

**Comment by mikker** [comment]
Jenkins, run the tests

**Comment by mikker** [comment]
jenkins, run the tests

**Comment by mikker** [comment]
Spec failure is unrelated.

Thank you for this, @matheussilvasantos !
