### PR TITLE
Close the read pipe at the right moment

### LINKED ISSUE #1350: Timeouts from APM server causes a file descriptor leak when HTTP compression is enabled
## Describe the bug

After the HTTP request to the APM server gets a time-out, `ElasticAPM::Transport::Connection` cannot close the _write_ pipe because it silently raises `Errno::EPIPE Exception: Broken pipe`.

## Steps to reproduce

1. Configure `ELASTIC_APM_SERVER_URL` so that you can get time-outs
2. Watch file descriptors to grow

## Expected behaviour

The number of file descriptors stays constant and does not grow continuously.

## Environment

- **OS**: Linux
- **Ruby version**: 3.2.0
- **Agent version**: 4.6.0

### PR DESCRIPTION
**Pull request by matheussilvasantos**
## What does this pull request do?

Closes the read pipe whether the HTTP request thread was executed or not.

## Why is it important?

If we only close the read pipe after the HTTP request inside the child thread, a file descriptor leak can happen.

## Checklist

- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).
- [x] My code follows the style guidelines of this project (See `.rubocop.yml`)
- [x] I have rebased my changes on top of the latest main branch

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-ruby/blob/main/CONTRIBUTING.md#testing) pass locally with my changes
- [x] I have made corresponding changes to the documentation
- [x] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
- [x] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)
- [x] Added an API method or config option? Document in which version this will be introduced

## Related issues

- Closes #1350

### CODE REVIEW

**Comment by estolfo** [comment]
jenkins please test

**Comment by matheussilvasantos** [comment]
Hi @estolfo, is there anything I have to fix on my side?

**Comment by estolfo** [comment]
Hi @matheussilvasantos thanks for following up. There are some test failures that I need to look at. They don't have to do with this code; it looks like one of the gems we test with dropped support for a version of Ruby we have in our test matrix.
I'll take a look at the test failures and have an update soon, but there's nothing I need from your side right now. Thanks again for your contribution!

**Comment by estolfo** [comment]
Hi @matheussilvasantos can you rebase against main now? The test failures have been resolved in the latest commit.

**Comment by matheus-silva-santos** [comment]
Hi @estolfo. I've rebased it.

**Comment by matheussilvasantos** [comment]
Hi @estolfo. I've rebased it.

**Comment by estolfo** [comment]
jenkins please test

File: lib/elastic_apm/transport/connection/http.rb [hunk 1]
```diff
@@ -75,7 +75,15 @@ def close(reason)
...
-          return if @request.nil? || @request&.join(5)
+
+          if @request&.join(5)
+            @rd&.close
+            return
+          end
+
+          @rd&.close
+
+          return if @request.nil?
```
Comment (estolfo) [inline lib/elastic_apm/transport/connection/http.rb:86]: I would suggest simplifying this to:

```ruby
          @request&.join(5) # will return nil if @request is nil, will return nil if 5s expires, will return the thread if the thread exits
          @rd&.close
          return if @request.nil?
```

because you will always call `@request&.join(5)` and then `@rd&.close` no matter what #join returns.

**Review by estolfo — CHANGES_REQUESTED** [review]

File: lib/elastic_apm/transport/connection/http.rb (hunk 1 above)
Comment (matheussilvasantos) [reply lib/elastic_apm/transport/connection/http.rb:86]: The condition before was `return if @request.nil? || @request&.join(5)`, so we need to return if `@request&.join(5)` returns a "truthy" value. `return if @request.nil?` won't make it return when `@request&.join(5)` returns a truthy value.

Comment (estolfo) [reply lib/elastic_apm/transport/connection/http.rb:86]: I understand now, thanks for the explanations.

**Comment by estolfo** [comment]
Thanks @matheussilvasantos !

**Comment by matheussilvasantos** [comment]
Thank you too, @estolfo. Do you intend to release it at RubyGems any time soon?

**Comment by estolfo** [comment]
@matheussilvasantos we just did a release within the last two weeks so I'm going to wait a little longer before doing another one, given that this is a bit of an edge case.

**Comment by matheussilvasantos** [comment]
Hi, again, Emily. Would you have an estimate of when you will release it? This caused issues in production once, and we want to avoid creating a dependency on GitHub by pointing our gem to the repo. Thanks!

**Comment by estolfo** [comment]
Hi @matheussilvasantos I was hoping to get [this issue](https://github.com/elastic/apm-agent-ruby/issues/1358) resolved and in the next release so was holding off. I'll give it a few more days and if it's not resolved by then, I'll do a release including this issue's fix.

**Comment by estolfo** [comment]
@matheussilvasantos v4.6.1 is released with this fix. Thanks again!

**Comment by matheussilvasantos** [comment]
@estolfo, thank you too!
